name: CI/CD Pipeline

on:
  push:          # Trigger on code push
    branches:
      - main
  pull_request:  # Trigger on pull requests
  schedule:      # Nightly health checks
    - cron: '0 0 * * *' # Runs at midnight daily

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu as the environment

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8

    # Step 4: Run tests
    - name: Run pytest
      run: pytest

    # Step 5: Run flake8
    - name: Lint code with flake8
      run: flake8 .
